Feature/cakephp challenge2
kamdam13/quelcode-cakephp pull request #2
Opened 2020-07-30 00:37 UTC by kamdam13

# CakePHP課題2の実装を行いましたのでレビューお願いします
## やったこと
- 取引後連絡機能を実装した
- ユーザー評価ページを実装した

## 設計書
https://docs.google.com/document/d/17v-OhDv_slvIuVieLgpLcpTiL76zaW2M_pDg2XuAWfw/edit?usp=sharing

## データベース定義書
https://docs.google.com/spreadsheets/d/1q7gOk70HKipNlxghkAB4_rfm-Yf5QmFyu23qSYNtmTk/edit?usp=sharing

2020-07-30 05:24 UTC, piasoratech requested changes
ユーザーの追加ができないので確認と修正をお願いします。

2020-07-30 05:27 UTC, kamdam13 commented
# PRを修正しました
## やったこと
- 6b9c500 のコミットでUsersコントローラのbeforeFilterにaddアクションとindexアクションを復元しました

2020-07-30 07:03 UTC, piasoratech requested changes
発送先連絡で電話番号欄に文字列が入るようになってしまっているので、そこはvalidationを追加しましょう。
設計時点での指摘漏れになってしまい申し訳ないですが、設計の修正を提出しそのあとコードの修正もお願いします。

2020-07-31 01:01 UTC, kamdam13 commented
# PRを更新しました
## やったこと
- b22326f のコミットで電話番号欄を数字に限りました

2020-07-31 02:09 UTC, himaru-jp requested changes
テンプレートですが、タブとスペースのインデントが混じっています。どちらかに統一をお願いします。

2020-07-31 02:09 UTC, himaru-jp commented on html/mycakeapp/src/Controller/AuctionController.php
> +		if(!isset($bidinfo) || !in_array($this->Auth->user('id'),[$reciever_id,$shipper_id])){
getの場合、取得できなかった時にCake\Datasource\Exception\RecordNotFoundExceptionが発生すると思います。
また、3行上で$bidinfoにアクセスしていることから、
```
!isset($bidinfo)
```
の判定は不要なように思われます。ご確認ください。

2020-07-31 02:09 UTC, himaru-jp commented on html/mycakeapp/src/Controller/RatingsController.php
> +		$this->loadModel('Bidinfo');
タブによるインデントが入っています。他と揃えましょう！

2020-07-31 02:09 UTC, himaru-jp commented on html/mycakeapp/src/Model/Table/BidinfoTable.php
> +            ->maxLength('reciever_phone_number',13)
13桁ということはハイフンが入ることを想定していますでしょうか？
であれば数字のみと整合性が合いません。
ご確認をお願いします。

2020-07-31 02:09 UTC, himaru-jp commented on html/mycakeapp/src/Controller/UsersController.php
> +		$this->set(compact('ratings'));
インデントがタブになっています。他と揃えましょう！

2020-07-31 02:09 UTC, himaru-jp commented on html/mycakeapp/src/Controller/UsersController.php
> +			'order' =>['created'=>'desc'],
インデントがタブになっています。他と揃えましょう！

2020-07-31 02:09 UTC, himaru-jp commented on html/mycakeapp/src/Controller/RatingsController.php
> +            if(!isset($bidinfo) || !in_array($this->Auth->user('id'),[$reciever_id,$shipper_id])){
他の箇所で指摘した通りです。

2020-07-31 02:48 UTC, kamdam13 commented
# PRを修正しました
## やったこと
- インデントのズレを修正しました
- reciever_phone_numberの文字数バリデーションを修正しました
- get()のエラー処理を追加しました

2020-07-31 03:33 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/RatingsController.php
> +        if ($this->request->is('post')) {
(修正不要)
ifがデカいですね！早期リターンを心がけましょうっ

2020-07-31 03:39 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/RatingsController.php
> +        if ($this->request->is('post')) {
```php
        if (!$this->request->is('post')) {
            return $this->redirect(['controller' => 'auction', 'action' => 'index']);
        }
        ...

2020-07-31 03:41 UTC, Yuzunoha commented on html/mycakeapp/src/Controller/UsersController.php
> +            }
(修正不要)
ここのelse節いらないですね！

2020-07-31 03:44 UTC, Yuzunoha approved these changes
LGTMです！！！
2件ほど修正不要のコメントをしているのでご確認くださいっ

2020-07-31 16:06 UTC, merged